# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'логин.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPoint, pyqtSignal, pyqtSlot
import sys


class Ui_Frame(object):
    def __init__(self, parent=None):
        self.login_successful = pyqtSignal()
        
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(316, 503)

        Frame.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Frame.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 491))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 290, 480))
        self.label.setStyleSheet("background-color: rgba(121, 133, 135, 240);\n"
"border-radius: 15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 270, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(85, 255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 330, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(85, 255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(60, 410, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgb(150, 150, 150);\n"
"color: rgba(255, 255, 255, 200);\n"
"border-radius: 5 px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"background-color: rgb(170, 170, 170);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 180, 180))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(0, 255, 255, 200)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 445, 141, 16))
        self.label_3.setStyleSheet("color:rgba(255, 255, 255, 150);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)        

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.lineEdit.setPlaceholderText(_translate("Frame", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("Frame", "Пароль"))
        self.pushButton.setText(_translate("Frame", "Вход"))
        self.label_2.setText(_translate("Frame", "👤"))
        self.label_3.setText(_translate("Frame", "Забыли логин или пароль?"))

    @pyqtSlot()
    def on_login_button_clicked(self):
        self.login_successful.emit()
    

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Frame()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
